// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: books.sql

package database

import (
	"context"
)

const getBooks = `-- name: GetBooks :many
SELECT id, title, author, filesize, extension, md5, year, language, pages, publisher, edition, coverurl, downloadurl, pageurl from books
`

func (q *Queries) GetBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Filesize,
			&i.Extension,
			&i.Md5,
			&i.Year,
			&i.Language,
			&i.Pages,
			&i.Publisher,
			&i.Edition,
			&i.Coverurl,
			&i.Downloadurl,
			&i.Pageurl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
